//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakefit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class all_lessons
    {
        public string name_of_teacher { get; set; }
        public System.DateTime date_of_lesson { get; set; }
        public string hour_of_lesson { get; set; }
        public string name_of_lesson { get; set; }
        public string kind_of_lesson { get; set; }
        public int id { get; set; }
        public string name_of_user { get; set; }
    }
}
