//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakefit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class close_of_saloon
    {
        public System.DateTime close_of_days { get; set; }
        public int id { get; set; }
    }
}
