//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakefit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public string name { get; set; }
        public string mail { get; set; }
        public string topic { get; set; }
        public string message { get; set; }
        public int id { get; set; }
        public string phone { get; set; }
        public System.DateTime date { get; set; }
    }
}
