//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakefit.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FakefitEntities6 : DbContext
    {
        public FakefitEntities6()
            : base("name=FakefitEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<all_lessons> all_lessons { get; set; }
        public DbSet<close_of_saloon> close_of_saloon { get; set; }
        public DbSet<contact> contact { get; set; }
        public DbSet<Lessons> Lessons { get; set; }
        public DbSet<permission_of_instructor> permission_of_instructor { get; set; }
        public DbSet<register> register { get; set; }
    }
}
