//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakefit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class register
    {
        public string name { get; set; }
        public string surname { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public int tall { get; set; }
        public int kg { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime finishdate { get; set; }
        public string user { get; set; }
        public int id { get; set; }
        public string phone { get; set; }
    }
}
